#!/bin/sh
# clean up all files that are easily regenerated by the make.sh script

name=$1
files="*~ demo *.log ${name}*.dst.txt ${name}*.html $name.txt ${name}*.tex
${name}_rst.* $name.rst $name.sphinx.rst $name.odt $name.md $name.st
$name.epytext ${name}.*wiki __tmp.do.txt ._tmp.do.txt ${name}*.ps ${name}*.pdf
_*.log *.aux *.bbl *.blg *.idx *.ilg *.ind tmp* ${name}*.log
${name}*.dvi *.out sphinx-rootdir collection_of_results.pdf tmp.*
automake_sphinx.* latex_figs *.ipynb *.toc *.bib *.dolog *.nav *.snm *.vrb
*.sty reveal.js ./${name} ./Trash _* Makefile make.bat conf.py index.rst auto" 
dir=`pwd`
echo "Removing in $dir:"
/bin/ls $files 2> /dev/null
rm -rf $files
